### ISSUE TITLE
FileSystem API (FS)

### ISSUE THREAD

**Issue by ghost** [caiiiycuk/js-dos.com#190]
Hello, I would like to ask for the js-dos 7 documentation API, particularly the FileSystem one (if you can publish it all, is better).
I would like to inject files inside the DOS filesystem, and retrieve them in a Javascript variable. I could overcome this issue in js-dos version 6.22 by using the fs.CreateFile() function, followed by a rescan command call, to refresh the DOS filesystem and preserve the directory stable, and could retrieve a file by converting it to a base64 code and typing it on console, then there was a callback, I do not remember well, something like onStdOut() or the like, that returned each printed character on screen, so I wrote begin-end markers to copy the base64 to a variable and decoded it in a Javascript variable.

This was too much overhead (the base64 encoded duplicates and the overhead for conversion). Does version 7 has a direct read/write API mechanism for the DOS filesystem to/from a Javascript variable to improve performance?

Thank you for your answer.

**Comment by caiiiycuk** [comment]
Hi I am not sure that understands you, why you need to convert files to base 64. Both js-dos v7 and 6.22 have support for [FS api](https://emscripten.org/docs/api_reference/Filesystem-API.html#id2) providen by emscripten.
So you can easily read/write files, do what you want. It support all POSIX functions.

However in js-dos v7 it can be used only in "direct" mode, because in worker mode you does not have direct access to emscripten module. This is [documentation](https://js-dos.com/v7/build/docs/dosbox-direct#accessing-file-system)

**Comment by ghost** [comment]
Because there are no readFile() or writeFile() functions defined in DOSFS API in js-dos 6.22:
https://js-dos.com/6.22/docs/api/generate.html?page=js-dos-fs

only createFile(), as I did. I did not know that there were other functions available, only the defined by the previous link.

It would be nice if you please copy some working examples of reading and writing files with js-dos version 6.22, because as you said, version 7 does not support accessing files in worker mode, and direct mode could block the page, so meanwhile it is more safe to stick to the 6.22 version and get some examples.

Thank you.

**Comment by ghost** [comment]
I have just figured out how to do it. It was simply using the variable fs inside the FS object.
Checked out with the console.log() browser output.

Thank you very much.

**Comment by caiiiycuk** [comment]
btw, you can switch to v7 if you want, it little bit faster in direct mode than 6.22
