### ISSUE TITLE
code

### ISSUE THREAD

**Issue by rail-master** [caiiiycuk/js-dos.com#23]
can i use your code on my website

**Comment by caiiiycuk** [comment]
Of course, feel free to do what you want :)

2 Июн 2017 г. 1:34 пользователь "rail-master" <notifications@github.com>
написал:

can i use your code on my website

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/caiiiycuk/js-dos.com/issues/23>, or mute the thread
