### ISSUE TITLE
Mouse tracking

### ISSUE THREAD

**Issue by dhewer** [caiiiycuk/js-dos.com#39]
Similarly to this issue: https://github.com/caiiiycuk/js-dos.com/issues/21

The mouse tracking seems off in some cases, one example:

https://www.dosgamesarchive.com/play/shooting-gallery/

Whether regular-sized or full screen, the mouse cursor in-game doesn't track with the visible Windows cursor. The difference between the game cursor and OS cursor is greater as the cursor approaches the bottom right corner.

I'm not sure if this is an emulator issue or a configuration issue? Thanks again for any assistance.

**Comment by dhewer** [comment]
This issue is fixed simply by using autolock: true ... not sure if this was the case way back in 2018 or not, but the mouse works fine with autolock enabled now. :)

**Comment by caiiiycuk** [comment]
Thanks!

**Comment by Ser-Gen** [comment]
I think this should be fixed.
Autolock is disabled on mobile.

**Comment by caiiiycuk** [comment]
@Ser-Gen what do you mean?

**Comment by Ser-Gen** [comment]
@caiiiycuk a position of the mouse pointer of OS doesn't match to position of the pointer in the game The Incredible Machine 2.

https://dos.zone/rep/my/the-incredible-machine-2-1994%40Incredible_Machine_2_floppy.jsdos%3AAaaQOw2FkaMfKu4sMn3IasKeEJx

https://user-images.githubusercontent.com/1856145/129444426-6890e21a-7af4-430b-8d28-da07b52718fb.mp4

As suggested in this comment, I can enable the `autolock` to hide this mismatch.
https://github.com/caiiiycuk/js-dos/issues/39#issuecomment-665207391

But the `autolock` doesn't work on touch devices. The position of tap will be wrong.

Should I create a separate issue? This problem is game-dependent.

**Comment by caiiiycuk** [comment]
Yes is better to create separate issue. However for some games it's not possible to sync browser cursor position and game cursor position. Only autolock can help.

**Comment by caiiiycuk** [comment]
BUT, looks like tim should works without autolock
